apiVersion: v1
kind: Service
metadata:
  name: chat-node-backend-service
spec:
  selector:
    app: chat-node-backend
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002
  type: LoadBalancer