apiVersion: v1
kind: Service
metadata:
  name: chat-node-frontend-service
spec:
  selector:
    app: chat-node-frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: LoadBalancer